# Generated by Django 5.0.6 on 2024-06-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['age_group'], name='onboarding__age_gro_3299a0_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['gender'], name='onboarding__gender_43bd97_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['parent_type'], name='onboarding__parent__5873b3_idx'),
        ),
    ]
